### ISSUE TITLE
Renamer instances are single use

### ISSUE THREAD

**Issue by jpenilla** [MinecraftForge/ForgeAutoRenamingTool#23]
The current API for inputs/outputs is somewhat restrictive for certain use cases. Here are a couple things I think could be useful improvements:
- Ability to re-use a Renamer instance for multiple jars (so we can only load libraries once)
- Batch (parallel if threads > 1) processing of jars (I guess this one can be an and/or with the previous point)
- Ability to process classes outside of jar files (as bytes ideally)

**Comment by LexManos** [comment]
FART isn't meant to be a all-cases renaming library. It is meant to be an executable jar that processes one file at a time.
So why would we need any of this?

**Comment by TheCurle** [comment]
Our tools are the bleeding edge of this technology. We're breaking new ground in a lot of the things we do, and it's entirely possible that FART is the first reliable, self contained (no other libraries required) tool of its kind that supports our modern formats. (ie, Srg2Source being rather unreliable, Lorenz/Atlas/Vignette being dependency hell, etc) 

In that case, I can see a case being made for us opening it to general purpose usage. In the grand scheme of things, it allows our tools to be used for more than what we do, and in theory doesn't require much modification (as long as it remains a tertiary goal, rather than a primary goal - we do have limited man hours to work on this).
